# Generated by Django 6.1

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(help_text='Unique student identifier (e.g. 2024-0001, IDSC-2024-01)', max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text="Student's first name", max_length=100)),
                ('last_name', models.CharField(help_text="Student's last name", max_length=100)),
                ('birth_date', models.DateField(blank=True, help_text='Date of birth (YYYY-MM-DD)', null=True)),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', help_text="Student's sex/gender", max_length=20)),
                ('course', models.CharField(help_text='Degree program or course (e.g. BSIT, BSCS, BSN)', max_length=100)),
                ('section', models.CharField(help_text='Class section (e.g. 3A, 1-1, CS401)', max_length=50)),
                ('contact_no', models.CharField(blank=True, default='', help_text='Contact number or mobile phone', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when student record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when student record was last updated')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students',
                'ordering': ['student_id'],
                'indexes': [
                    models.Index(fields=['last_name', 'first_name'], name='idx_student_name'),
                    models.Index(fields=['course', 'section'], name='idx_student_course_sec'),
                ],
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('health_id', models.BigAutoField(help_text='Unique health record identifier', primary_key=True, serialize=False)),
                ('allergies', models.TextField(blank=True, default='', help_text='Known allergies (e.g. penicillin, peanuts, pollen)')),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('Unknown', 'Unknown')], default='', help_text='Blood type (e.g. A+, O+, etc.)', max_length=10)),
                ('medical_history', models.TextField(blank=True, default='', help_text='Past medical history and chronic conditions (e.g. Asthma, Hypertension)')),
                ('medication', models.TextField(blank=True, default='', help_text='Current medications and prescriptions')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms (kg)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('500.0'))])),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in centimeters (cm)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('300.0'))])),
                ('visit', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of clinic visit')),
                ('consultation', models.TextField(blank=True, default='', help_text='Clinic consultation notes, diagnosis, and treatment provided')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when health record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when health record was last updated')),
                ('student', models.ForeignKey(db_column='student_id', help_text='The student associated with this health record', on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='clinic.student')),
            ],
            options={
                'verbose_name': 'Health Record',
                'verbose_name_plural': 'Health Records',
                'db_table': 'health_records',
                'ordering': ['-visit', '-health_id'],
                'indexes': [
                    models.Index(fields=['student', '-visit'], name='idx_hr_student_visit'),
                    models.Index(fields=['-visit'], name='idx_hr_visit'),
                ],
            },
        ),
    ]
