# Generated by Django 6.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.BigAutoField(
                help_text='Auto-incrementing unique student identifier',
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
