# Generated by Django 6.1 on 2026-09-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_student_student_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='student',
            name='idx_student_name',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='idx_student_course_sec',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.BigIntegerField(help_text='Externally supplied unique student identifier', primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='student',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='contact_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='section',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sex',
        ),
    ]
