# Generated by Django 6.1 on 2026-08-30 14:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_student_student_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('medicine_id', models.BigAutoField(help_text='Unique medicine identifier', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Medicine name', max_length=150)),
                ('generic_name', models.CharField(blank=True, default='', help_text='Generic name of the medicine', max_length=150)),
                ('unit', models.CharField(help_text='Unit of measurement (e.g. tablet, capsule, bottle)', max_length=50)),
                ('quantity_in_stock', models.PositiveIntegerField(default=0, help_text='Current quantity available in stock')),
                ('reorder_level', models.PositiveIntegerField(default=10, help_text='Stock level at which medicine is considered low stock')),
                ('expiration_date', models.DateField(blank=True, help_text='Medicine expiration date', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this medicine is currently available for dispensing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
                'db_table': 'medicines',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='idx_medicine_name'), models.Index(fields=['quantity_in_stock'], name='idx_medicine_stock')],
            },
        ),
        migrations.CreateModel(
            name='DispensingRecord',
            fields=[
                ('dispensing_id', models.BigAutoField(help_text='Unique dispensing record identifier', primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity of medicine dispensed')),
                ('dispensed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, default='', help_text='Additional notes about the dispensing')),
                ('dispensed_by', models.ForeignKey(help_text='User who dispensed the medicine', on_delete=django.db.models.deletion.PROTECT, related_name='dispensing_records', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(db_column='student_id', help_text='Student who received the medicine', on_delete=django.db.models.deletion.PROTECT, related_name='dispensing_records', to='clinic.student')),
                ('medicine', models.ForeignKey(db_column='medicine_id', help_text='Medicine that was dispensed', on_delete=django.db.models.deletion.PROTECT, related_name='dispensing_records', to='clinic.medicine')),
            ],
            options={
                'db_table': 'dispensing_records',
                'ordering': ['-dispensed_at', '-dispensing_id'],
                'indexes': [models.Index(fields=['student', '-dispensed_at'], name='idx_disp_student_date'), models.Index(fields=['medicine', '-dispensed_at'], name='idx_disp_medicine_date')],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('transaction_id', models.BigAutoField(help_text='Unique stock transaction identifier', primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('STOCK_IN', 'Stock In'), ('DISPENSE', 'Dispense'), ('ADJUSTMENT', 'Adjustment')], help_text='Type of stock transaction', max_length=20)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity involved in the transaction')),
                ('previous_stock', models.PositiveIntegerField(help_text='Stock quantity before the transaction')),
                ('new_stock', models.PositiveIntegerField(help_text='Stock quantity after the transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, default='', help_text='Additional notes about the transaction')),
                ('created_by', models.ForeignKey(help_text='User who performed the transaction', on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to=settings.AUTH_USER_MODEL)),
                ('medicine', models.ForeignKey(db_column='medicine_id', help_text='Medicine affected by the transaction', on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='clinic.medicine')),
            ],
            options={
                'db_table': 'stock_transactions',
                'ordering': ['-created_at', '-transaction_id'],
                'indexes': [models.Index(fields=['medicine', '-created_at'], name='idx_stock_medicine_date'), models.Index(fields=['transaction_type', '-created_at'], name='idx_stock_type_date')],
            },
        ),
    ]
