# Generated by Django 6.1.1 on 2026-09-22 07:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_medicine_dispensingrecord_stocktransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='medical_history',
            field=models.TextField(blank=True, default='', help_text='Past medical history and chronic conditions'),
        ),
        migrations.CreateModel(
            name='MedicineDispensation',
            fields=[
                ('dispensation_id', models.BigAutoField(help_text='Unique medicine dispensation identifier', primary_key=True, serialize=False)),
                ('healthrecord_id', models.BigIntegerField(blank=True, help_text='Optional Clinic health record identifier', null=True)),
                ('student_id', models.PositiveIntegerField(help_text='Student identifier supplied by the Registrar System')),
                ('medicine_id', models.PositiveIntegerField(help_text='Medicine/product identifier supplied by the Inventory System')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity of medicine dispensed', validators=[django.core.validators.MinValueValidator(1)])),
                ('dispensed_at', models.DateTimeField(help_text='Date and time when the medicine was dispensed')),
                ('reason', models.TextField(blank=True, help_text='Reason for dispensing the medicine', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the dispensation record was created')),
            ],
            options={
                'db_table': 'medicine_dispensations',
                'ordering': ['-dispensed_at', '-dispensation_id'],
                'indexes': [models.Index(fields=['student_id', '-dispensed_at'], name='idx_md_student_date'), models.Index(fields=['medicine_id', '-dispensed_at'], name='idx_md_medicine_date')],
            },
        ),
    ]
