# Generated by Django 6.1 on 2026-09-18 00:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_remove_student_idx_student_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthStatus',
            fields=[
                ('status_id', models.BigAutoField(help_text='Unique health status identifier', primary_key=True, serialize=False)),
                ('health_status', models.TextField(blank=True, default='', help_text='Health status details reported for the student')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time the health status was recorded')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when health status was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when health status was last updated')),
                ('student', models.ForeignKey(db_column='student_id', help_text='The student associated with this health status', on_delete=django.db.models.deletion.CASCADE, related_name='health_statuses', to='clinic.student')),
            ],
            options={
                'verbose_name': 'Health Status',
                'verbose_name_plural': 'Health Statuses',
                'db_table': 'health_statuses',
                'ordering': ['-date', '-status_id'],
                'indexes': [models.Index(fields=['student', '-date'], name='idx_hs_student_date'), models.Index(fields=['-date'], name='idx_hs_date')],
            },
        ),
    ]
