# Generated by Django 6.1 on 2026-09-22 04:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def move_visit_and_consultation_to_consultations(apps, schema_editor):
    """
    Move existing health_record visit/consultation data into the new
    consultations table before those fields are dropped from health_records.
    """
    HealthRecord = apps.get_model('clinic', 'HealthRecord')
    Consultation = apps.get_model('clinic', 'Consultation')

    for record in HealthRecord.objects.all().iterator():
        Consultation.objects.create(
            student_id=record.student_id,
            consultation=record.consultation or '',
            visits=record.visit or django.utils.timezone.now(),
        )


def reverse_move_consultations_to_health_records(apps, schema_editor):
    """
    Reverse move: restore consultation/visit data back into the latest
    health record of each affected student.
    """
    HealthRecord = apps.get_model('clinic', 'HealthRecord')
    Consultation = apps.get_model('clinic', 'Consultation')

    for consultation in Consultation.objects.all().iterator():
        record = (
            HealthRecord.objects
            .filter(student_id=consultation.student_id)
            .order_by('-health_id')
            .first()
        )
        if record is not None:
            record.consultation = consultation.consultation
            record.visit = consultation.visits
            record.save()


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_healthstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('consultation_id', models.BigAutoField(help_text='Unique consultation identifier', primary_key=True, serialize=False)),
                ('consultation', models.TextField(blank=True, default='', help_text='Clinic consultation notes, diagnosis, and treatment provided')),
                ('visits', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of clinic visit')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when consultation was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when consultation was last updated')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'db_table': 'consultations',
                'ordering': ['-visits', '-consultation_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='healthrecord',
            options={'ordering': ['-health_id'], 'verbose_name': 'Health Record', 'verbose_name_plural': 'Health Records'},
        ),
        migrations.RemoveIndex(
            model_name='healthrecord',
            name='idx_hr_student_visit',
        ),
        migrations.RemoveIndex(
            model_name='healthrecord',
            name='idx_hr_visit',
        ),
        migrations.AddIndex(
            model_name='healthrecord',
            index=models.Index(fields=['student', '-health_id'], name='idx_hr_student_id'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='student',
            field=models.ForeignKey(db_column='student_id', help_text='The student associated with this consultation', on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='clinic.student'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['student', '-visits'], name='idx_c_student_visit'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['-visits'], name='idx_c_visit'),
        ),
        migrations.RunPython(
            move_visit_and_consultation_to_consultations,
            reverse_move_consultations_to_health_records,
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='consultation',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='visit',
        ),
    ]